apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: voting-application
  labels:
    app: redis-db
spec:
  type: ClusterIP
  ports:
    - name: redis-svc-port
      port: 6379
      targetPort: 6379
  selector:
    app: redis-db


    