apiVersion: v1
kind: Service
metadata:
  name: voting-lb-service
  namespace: voting-application
  labels:
    apps: voting-app
spec: 
  ports:
    - port: 5000
      targetPort: 80
      protocol: TCP
      name: voteing-service
  type: LoadBalancer
  selector:
    app: voting-app