apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  namespace: voting-application
  labels:
    app: voting-app
spec:
  type: NodePort
  ports:
    - name: voting-svc-port
      port: 80
      targetPort: 80
      nodePort: 31000
      protocol: TCP
  selector:
    app: voting-app

    