apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  namespace: voting-application
  labels:
    app: worker-app
spec:
  template:
    metadata:
      name: worker-app
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker-container
          image: noura93/worker:latest
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
